### ISSUE TITLE
feature request: support multiple -S

### ISSUE THREAD

**Issue by lark** [schweikert/fping#100]
For a multi-home server, multiple fping instances are required to checking reachability and packet loss rate via different paths to a target or targets.

If multiple -S is supported, this can be easier. For example:

`fping -S addr1 target -S addr2 target -S addr3 target`

-S applies to targets following it until another -S takes effect.

**Comment by schweikert** [comment]
I am not sure that this is worth the effort. It also makes the usage of fping more complicated (how to distinguish the results, for example?). It seems to me that running multiple fping instances is both easier and simpler.
