### ISSUE TITLE
Usage prints inconsistent information in version 2.4b2_to $Date: 2001/01/25 11:25:04

### ISSUE THREAD

**Issue by eddiebroeder** [schweikert/fping#103]
When I run ```fping --help```, I see
```    -r n       number of retries (default 3) ```

but when I run ```fping -r0```, I see
```  -r n       number of retries (default 3) ```

**Comment by schweikert** [comment]
This version is obsolete, from my point of view. Please reopen if you can reproduce with a current version of fping.
