### ISSUE TITLE
fping on Amazon Machine Instance 2016.09 fails to compile

### ISSUE THREAD

**Issue by ktsaou** [schweikert/fping#108]
Hi,

I get this:

```sh
./autogen.sh 
configure.ac:31: installing './config.guess'
configure.ac:31: installing './config.sub'
configure.ac:32: installing './install-sh'
configure.ac:32: installing './missing'
automake: warnings are treated as errors
src/Makefile.am:16: warning: compiling 'fping.c' with per-target flags requires 'AM_PROG_CC_C_O' in 'configure.ac'
src/Makefile.am: installing './depcomp'
autoreconf: automake failed with exit status: 1
```

Adding `AM_PROG_CC_C_O` to `configure.ac` fixes the issue.

I see it added with commit: https://github.com/schweikert/fping/commit/649922393cc614cb02d23f26fc110d9692ec3367

But it is not currently merged.

Have I missed something?

**Comment by schweikert** [comment]
commit 6499223 was committed/merged in the master branch  (I didn't notice it). I have now also merged it in the develop branch, and will soon make a release.
