### ISSUE TITLE
Retreiving fping data

### ISSUE THREAD

**Issue by sgalam7** [schweikert/fping#115]
i have added the fping plugin and got 3 dashboards on fping (fping.netdata_latency, quality and packets).
Is there any way that i can retrieve this data in a seperate html page? I tried to create a new html using below parameters, and it didn't work. Any help is much appreicated. Thanks

                     <div data-netdata="fping.netdata_latency"
                     data-title="Latency on Netdata Server"
                    data-chart-library="dygraph"
                    data-width="49%"
                    data-height="100%"
                    data-after="-300"
                    data-dygraph-valuerange="[0, 100]"
                    ></div>

**Comment by ktsaou** [comment]
hm... I guess this issue belongs to the netdata project.
Could you please close it here and open it there?
