### ISSUE TITLE
zero retry fails (wrong) and doesn't report the reason (also wrong)

### ISSUE THREAD

**Issue by gitcnd** [schweikert/fping#119]
The following fails:-

 fping -r 0 8.8.8.8

without explaining why (just throws up the help screen - which does not help anyone).

Same problem with other parms which should also accept zero.

Zero is a valid option for this switch - so it should be explicitly accepted.

Errors should always explain the error (end end the process with an appropriate exit code), not just jump lazily to a help screen.

**Comment by schweikert** [comment]
I can’t reproduce the problem with fping -r 0. What version are you using?
