### ISSUE TITLE
Is it possible to compile fping to use -R option( --random) by default?

### ISSUE THREAD

**Issue by bessome** [schweikert/fping#126]
Hello
Is it possible to compile fping to use -R option( --random) by default?

**Comment by xianginx** [comment]
No Possible

**Comment by schweikert** [comment]
I think this should be best implemented by writing a wrapper, instead of modifying the binary. If you still want to do it, it’s quite easy though:

    --- a/src/fping.c                                                                                                         
    +++ b/src/fping.c                                                                                                         
    @@ -290,7 +290,7 @@ int per_recv_flag, report_all_rtts_flag, name_flag, addr_flag, backoff_flag, rdn                      
     int multif_flag, timeout_flag;                                                                                           
     int outage_flag = 0;                                                                                                     
     int timestamp_flag = 0;                                                                                                  
    -int random_data_flag = 0;                                                                                                
    +int random_data_flag = 1;                                                                                                
     #if defined(DEBUG) || defined(_DEBUG)                                                                                    
     int randomly_lose_flag, sent_times_flag, trace_flag, print_per_system_flag;                                              
     int lose_factor;
