### ISSUE TITLE
How to make fping result always sequential in accordance origin of value

### ISSUE THREAD

**Issue by ras24** [schweikert/fping#127]
I want to get result of fping always sequential in accordance with origin of value.

command :

    fping -e 151.101.129.164 8.8.8.8

result :

    8.8.8.8 is alive (5.43 ms)
    151.101.129.164 is alive (63.2 ms)

The result above is different with the fping command, where `151.101.129.164` put in the first fping command but the result show in the second.

How can the `151.101.129.164` display first in result without change the order of the fping command or maybe have another options?

**Comment by schweikert** [comment]
You can use —count 1 for example to get results in the order that you specified.
