### ISSUE TITLE
is it possible to ping with packet count of 3 but get only average result in output ?

### ISSUE THREAD

**Issue by from88** [schweikert/fping#128]
hello,

is it possible to ping with packet count of 3 but get only average result in output ?

For example:` fping -C 3 -A -q 8.8.8.8`, and instead of this output:

`8.8.8.8 : 10.65 10.64 10.65`

Get average ouput:

`8.8.8.8 : 10.65 `

**Comment by schweikert** [comment]
You can use “-c” instead of “-C”
