### ISSUE TITLE
Fping checksum error

### ISSUE THREAD

**Issue by be6ana** [schweikert/fping#137]
I'm using fping for Smokeping and one of my end devices show me this :

13:05:12.660473 IP (tos 0x0, ttl 63, id 43857, offset 0, flags [none], proto ICMP (1), length 84)
    172.16.17.1 > 10.16.1.8: ICMP echo request, id 60117, seq 6, length 64
13:05:12.661142 IP (tos 0x0, ttl 64, id 59522, offset 0, flags [none], proto ICMP (1), length 84)
    10.16.1.8 > 172.16.17.1: ICMP echo reply, id 60117, seq 6, length 64 (wrong icmp cksum ffff (->1524)!)
13:05:14.686471 IP (tos 0x0, ttl 63, id 9107, offset 0, flags [none], proto ICMP (1), length 84)
    172.16.17.1 > 10.16.1.8: ICMP echo request, id 60117, seq 199, length 64
13:05:14.687195 IP (tos 0x0, ttl 64, id 59523, offset 0, flags [none], proto ICMP (1), length 84)
    10.16.1.8 > 172.16.17.1: ICMP echo reply, id 60117, seq 199, length 64 (wrong icmp cksum ffff (->1463)!)
13:05:16.711837 IP (tos 0x0, ttl 63, id 29560, offset 0, flags [none], proto ICMP (1), length 84)
    172.16.17.1 > 10.16.1.8: ICMP echo request, id 60117, seq 392, length 64
13:05:16.712408 IP (tos 0x0, ttl 64, id 59524, offset 0, flags [none], proto ICMP (1), length 84)
    10.16.1.8 > 172.16.17.1: ICMP echo reply, id 60117, seq 392, length 64 (wrong icmp cksum ffff (->13a2)!)
13:05:18.740683 IP (tos 0x0, ttl 63, id 29639, offset 0, flags [none], proto ICMP (1), length 84)
    172.16.17.1 > 10.16.1.8: ICMP echo request, id 60117, seq 585, length 64
13:05:18.741897 IP (tos 0x0, ttl 64, id 59525, offset 0, flags [none], proto ICMP (1), length 84)
    10.16.1.8 > 172.16.17.1: ICMP echo reply, id 60117, seq 585, length 64 (wrong icmp cksum ffff (->12e1)!)
13:05:20.771340 IP (tos 0x0, ttl 63, id 63043, offset 0, flags [none], proto ICMP (1), length 84)
    172.16.17.1 > 10.16.1.8: ICMP echo request, id 60117, seq 778, length 64
13:05:20.772236 IP (tos 0x0, ttl 64, id 59526, offset 0, flags [none], proto ICMP (1), length 84)
    10.16.1.8 > 172.16.17.1: ICMP echo reply, id 60117, seq 778, length 64 (wrong icmp cksum ffff (->1220)!)
13:05:22.793894 IP (tos 0x0, ttl 63, id 29811, offset 0, flags [none], proto ICMP (1), length 84)
    172.16.17.1 > 10.16.1.8: ICMP echo request, id 60117, seq 971, length 64
13:05:22.794266 IP (tos 0x0, ttl 64, id 59527, offset 0, flags [none], proto ICMP (1), length 84)
    10.16.1.8 > 172.16.17.1: ICMP echo reply, id 60117, seq 971, length 64 (wrong icmp cksum ffff (->115f)!)

and of course host is unreachable. 

But if i use ping  - everithing is ok. Why ?

13:08:08.003188 IP (tos 0x0, ttl 63, id 9931, offset 0, flags [none], proto ICMP (1), length 84)
    172.16.17.1 > 10.16.1.8: ICMP echo request, id 11243, seq 0, length 64
13:08:08.004235 IP (tos 0x0, ttl 64, id 59564, offset 0, flags [none], proto ICMP (1), length 84)
    10.16.1.8 > 172.16.17.1: ICMP echo reply, id 11243, seq 0, length 64
13:08:09.004935 IP (tos 0x0, ttl 63, id 32861, offset 0, flags [none], proto ICMP (1), length 84)
    172.16.17.1 > 10.16.1.8: ICMP echo request, id 11243, seq 1, length 64
13:08:09.006072 IP (tos 0x0, ttl 64, id 59565, offset 0, flags [none], proto ICMP (1), length 84)
    10.16.1.8 > 172.16.17.1: ICMP echo reply, id 11243, seq 1, length 64
13:08:10.006017 IP (tos 0x0, ttl 63, id 32867, offset 0, flags [none], proto ICMP (1), length 84)
    172.16.17.1 > 10.16.1.8: ICMP echo request, id 11243, seq 2, length 64
13:08:10.007018 IP (tos 0x0, ttl 64, id 59566, offset 0, flags [none], proto ICMP (1), length 84)
    10.16.1.8 > 172.16.17.1: ICMP echo reply, id 11243, seq 2, length 64
13:08:11.007773 IP (tos 0x0, ttl 63, id 32868, offset 0, flags [none], proto ICMP (1), length 84)
    172.16.17.1 > 10.16.1.8: ICMP echo request, id 11243, seq 3, length 64
13:08:11.008764 IP (tos 0x0, ttl 64, id 59567, offset 0, flags [none], proto ICMP (1), length 84)
    10.16.1.8 > 172.16.17.1: ICMP echo reply, id 11243, seq 3, length 64

**Comment by schweikert** [comment]
I have no idea... The checksum should be correct, otherwise fping would be not useable for anybody. What operating system are you using? What fping version? Are you using it with sudo or capabilities? Do you see the packets malformed already on the sending host?
