### ISSUE TITLE
Ability to set fwmark on outgoing packets

### ISSUE THREAD

**Issue by logan2211** [schweikert/fping#158]
Hello,

Many diagnostic tools like iputils-ping[1], traceroute[2], and mtr[3] support `mark` or `--fwmark` parameters which can be used by iproute2 to perform policy routing for outbound packets. It would be great if fping could begin supporting fwmark for outbound packets to facilitate easier policy routing decisions.

[1] https://manpages.ubuntu.com/manpages/bionic/man8/ping.8.html
[2] https://manpages.ubuntu.com/manpages/bionic/man1/traceroute.db.1.html
[3] https://manpages.ubuntu.com/manpages/bionic/man8/mtr.8.html

**Comment by auerswal** [comment]
Pull request #289 has just been merged. The new option `-k`, `--fwmark` should implement the requested functionality.
@logan2211: Can this issue be closed?
