### ISSUE TITLE
feature request: print timeout in loop or count mode (like Windows ping), and output to telegraf

### ISSUE THREAD

**Issue by Jimmy-Z** [schweikert/fping#161]
I'm willing to write these features and submit a pull request, but I wonder if you would merge this. If not, I'm a bit hesitated to maintain a fork.

I should probably open 2 different issues but it's a bit related.

If only for the 2nd feature, I could write a script to parse the output of fping and reformat it to influxdb line format and it's done. But without timeout messages, it's a bit hard for the visualizer(grafana) to figure out the loss rate for a given duration.

For the 1st feature, I had to patch fping, it shouldn't be too hard from a glance of the code, back off is disabled for loop mode (the mode I intended to use) and count mode, then seq_map becomes naturally sorted by ETA, so every time a timeout happens, print and zero out the tail of it.

The 1st feature seems more likely to be merged I guess, the 2nd one seems not.

There is an official ping plugin from telegraf but it's too slow/heavy for the number of hosts I'd like to watch.

**Comment by schweikert** [comment]
first feature will be part of fping 5.0 (implemented in 43f6e3). For the second feature, please open a separate issue.
