### ISSUE TITLE
[Feature Request] Stop pinging if N hosts are reachable

### ISSUE THREAD

**Issue by mirfatif** [schweikert/fping#171]
In combination with `--reachable=N` it would save time on large networks. E.g. with `fping --retry=5 --timeout=200 --reachable=2 --generate 192.168.1.0/24` if router responds at `192.168.1.1` and any other host at DHCP assigned IP - say `192.168.1.10` - do not retry and wait for timeout on other hosts.

**Comment by gsnw** [comment]
I have created a new pull request #260 with complete copy of the code and a corresponding test case

**Comment by mirfatif** [comment]
I'm not currently using `fping`. If the functionality has been added, please close.
