### ISSUE TITLE
fping6 -6 gives misleading error message

### ISSUE THREAD

**Issue by xtaran** [schweikert/fping#176]
Initially [reported in Debian as #955436](https://bugs.debian.org/955436) by @Zugschlus:

> ```
> [1/5592]mh@drop:~ $ fping6 -6 2a01:238:42bc:a101::1
> fping6: can't specify both -4 and -6
> 1 [2/5593]mh@drop:~ $ fping6 2a01:238:42bc:a101::1
> 2a01:238:42bc:a101::1 is alive
> [3/5594]mh@drop:~ $ fping 2a01:238:42bc:a101::1
> 2a01:238:42bc:a101::1 is alive
> [4/5595]mh@drop:~ $ fping -6 2a01:238:42bc:a101::1
> 2a01:238:42bc:a101::1 is alive
> [5/5596]mh@drop:~ $ fping -6 -6 2a01:238:42bc:a101::1
> fping: can't specify both -4 and -6
> 1 [6/5597]mh@drop:~ $
> ```
>
> The code should handle the same address family option given twice in a more graceful way.

**Comment by rplessl** [comment]
Duplicate of #149 and #147

**Comment by xtaran** [comment]
> Duplicate of #149 and #147

Thanks for making me aware of this being already fixed. Will update the Debian bug report accordingly.
