### ISSUE TITLE
Packet size doesn't display over 4096 bytes

### ISSUE THREAD

**Issue by Shourai** [schweikert/fping#180]
When running fping with a packet size of over 4096 bytes, it doesn't
correctly display the size and always defaults to displaying 4096.

So when I run `fping -c 10 -M -b 9000`, to check jumbo frames.
`[0], 4090 bytes, 0.03 ms (0.03 avg, 0% loss)`

However if I run a tcpdump I do see that the package size does go over 4096 bytes.
`ICMP echo request, id 11483, seq 0, length 9008`

**Comment by schweikert** [comment]
fixed in a136764f (to be released with fping 5.0)
