### ISSUE TITLE
Reachability status are not reliable when we execute the fping in parallel 

### ISSUE THREAD

**Issue by vthangar0202** [schweikert/fping#183]
We are hitting this issue in Fping Version 4.2.

for one our requirement , we are doing icmp ping in batch by batch (60 devices ip per batch) with multiple java thread.

in this case , we are getting the status as alive even if the particular IP is un-reachable.  if i ping that device alone immediately , its showing the status as Un-reachable. Hitting this issue inconsistently.  Any known issues? Please let me know.

**Comment by vthangar0202** [comment]
Same scenario is working fine with the fping version 3.10

**Comment by tycho** [comment]
I think this is a side effect of https://github.com/schweikert/fping/commit/1486bf209baa49724c7f776463d2ba5858fa0ff4

That commit should be reverted until we can do it properly. I've got some work-in-progress stuff in my own tree to that end.

**Comment by schweikert** [comment]
@tycho note that 1486bf2 is not part of fping 4.2, but it could be the same issue that you wanted to fix with that patch.

**Comment by tycho** [comment]
Well maybe it's a different issue then, but the symptoms are similar. If I did fping in parallel after commit 1486bf2, sometimes different fping processes would incorrectly think that the response was intended for them. I added this commit in my tree which resolved it there: https://github.com/tycho/fping/commit/d2dda2d99a96cfd2fbfc031b4b784f008fdbf2d9

**Comment by schweikert** [comment]
Can you reproduce with fping 5.0?

**Comment by mhusmann** [comment]
I had the same issue running fping 4.3-1. Now I upgraded to version 5 and the reachability status is fine again when running fping in parallel.
