### ISSUE TITLE
output not send to stdout, with  `-C` `-c`

### ISSUE THREAD

**Issue by Eideen** [schweikert/fping#184]
If  `-C`  or `-c` is used the output is not what i expected.

I expecte the result to be sent to stdout.

### CMD: `TEST=$(fping 192.168.2.1 -C3) ;echo; echo $TEST`
Result
````bash

192.168.2.1 : 0.54 0.37 0.41

192.168.2.1 : [0], 84 bytes, 0.54 ms (0.54 avg, 0% loss) 192.168.2.1 : [1], 84 bytes, 0.37 ms (0.45 avg, 0% loss) 192.168.2.1 : [2], 84 bytes, 0.41 ms (0.44 avg, 0% loss)
````
First line is result, 
second, is the verbose output.

### CMD: `TEST=$(fping 192.168.2.1 -c3) ;echo; echo $TEST`

````bash

192.168.2.1 : 0.54 0.37 0.41

192.168.2.1 : [0], 84 bytes, 0.54 ms (0.54 avg, 0% loss) 192.168.2.1 : [1], 84 bytes, 0.37 ms (0.45 avg, 0% loss) 192.168.2.1 : [2], 84 bytes, 0.41 ms (0.44 avg, 0% loss)
````
First line is result, 
second, is the verbose output.

### CMD: `TEST=$(fping 192.168.2.1 -C3 -q) ;echo; echo $TEST`
Result no output
### CMD: `TEST=$(fping 192.168.2.1 -c3 -q) ;echo; echo $TEST`
Result no output

test on `fping: Version 4.1`

**Comment by schweikert** [comment]
I agree that fping's use of stderr is not ideal, but we can't change it because of compatibility reasons (see also #9, which we had to revert).
