### ISSUE TITLE
[RFC] compatibility issue with stdout stderr

### ISSUE THREAD

**Issue by Torstein-Eide** [schweikert/fping#189]
#184 #188 
I think we should to break the compatibility of some programmes that uses a design "error", where all of the output send to stderr instead of stdout.

We can do this over  period to allow migration to what is expected, for new users and programmers, to be inline with standard practises.

I think we can do the following:

1. Add a new flag for output to stdout (`--stdout` or  `--new`)and stderr (`--stderr` or `--old`), and add a warning to stderr that it will changed, in sometime. and warning to stdout about some of the output is not print to stdout without `--stdout` flag.
1. change the default to `--stdout`.
1. delete the old `--stderr`

**Comment by schweikert** [comment]
I am against breaking backwards compatibility, even with a transition effort. I think the pain is not worth the effort.

**Comment by Eideen** [comment]
I think we should start with adding a option to use stdout, and info about the unusual output is done. so novice fping users know that there is  unusual thing with fping.
