### ISSUE TITLE
-I option should support setting a source IP (not only interface)

### ISSUE THREAD

**Issue by schweikert** [schweikert/fping#2]
fping should behave like iptools's ping for option -I: when an interface is given, then bind to that interface (as implemented already), if an IP address is given, then use that as source IP address.

**Comment by malisettirammurthy** [comment]
Hi Schweikert,

Do we have an fping executable for windows platform for the latest version of the fping?

It looks like we have exe with version-3.0.0. If there is any latest version executable, could you update here please.

Actually, I am looking for an executable having -S option available.

Thanks,
Ram Murthy
