### ISSUE TITLE
Add option to append to log file

### ISSUE THREAD

**Issue by mcsilver** [schweikert/fping#213]
As a user, I want (the option) to append to an existing log file so that I can call fping in a batch file many times without losing the previous results.

**Comment by schweikert** [comment]
Can't you use shell output redirection for this?

**Comment by mcsilver** [comment]
Sorry, I didn't see your question so long ago.

I think the reason for the request was to output to both STDOUT and a log file, which fping's -L switch does, but not with an append option.

FYI, I ended up finding a Windows port of the Linux command tee (tee.exe) and redirected to that for output to both STDOUT and the file.
