### ISSUE TITLE
PATCH: fix getnameinfo

### ISSUE THREAD

**Issue by aafbsd** [schweikert/fping#218]
getnameinfo() is not called properly for IPv4 (didn't check v6).

[patch-d-fix_getnameinfo.txt](https://github.com/schweikert/fping/files/6382239/patch-d-fix_getnameinfo.txt)

You might also want to check the result code, call gai_strerror() and inform the user if s.th. goes wrong

**Comment by schweikert** [comment]
Could you create a pull request?

**Comment by aafbsd** [comment]
I am no real git or github user so this is a first wild guess. Whatever I messed up should be fixable. Constructive criticism is always welcome :-).

**Comment by gsnw** [comment]
Pull request: #227

**Comment by gsnw** [comment]
@schweikert you can close this issue. That fixed with pull request #227
