### ISSUE TITLE
I like psping in windows, could you please add TCP ping suport for fping

### ISSUE THREAD

**Issue by tlsalex** [schweikert/fping#238]
I usually use psping (a tool from microsoft sysinternal) to test website response time which is based on a tcp connection on windows.

It's really more useful than the normal ping.

I really hope fping can do that, too.

Thanks.

**Comment by schweikert** [comment]
I don't want to extend fping with more probing types and keep it focused on ICMP. The goal is to keep fping small and easy to maintain.
