### ISSUE TITLE
Man-Page on www.fping.org is quite old

### ISSUE THREAD

**Issue by auerswal** [schweikert/fping#239]
The man-page at https://www.fping.org/fping.1.html is quite old, it still contains the typo `--quet` fixed in May 2017. Thus it is missing the documentation for some options, e.g., `-x`, and some additional fixes, e.g., `-s, --stats`.

GitHub seems to render the POD file sufficiently well that you could probably replace the HTML man-page with a link to the current `fping.pod` similar to the link to the latest ChangeLog file instead of having to update an additional copy at https://www.fping.org/fping.1.html.

(BTW the https://www.fping.org homepage currently lists version 5.0 as the latest release and does not provide version 5.1 in https://www.fping.org/dist/ while there is a 5.1 release on GitHub.)

**Comment by xtaran** [comment]
> (BTW the https://www.fping.org homepage currently lists version 5.0 as the latest release and does not provide version 5.1 in https://www.fping.org/dist/ while there is a 5.1 release on GitHub.)

This is also the reason why Debian Unstable still has version 5.0 — Debian's `uscan` tool can only check one URL per upstream and I so far used the download directory on https://www.fping.org/ — shall I use Github's fping release page instead?

**Comment by schweikert** [comment]
I am a bit delayed with the release of the fping 5.1 artifacts because the release process was using travic-ci and bintray, which are both obsolete now... I am working on moving to GitHub Actions and I should soon finish the 5.1 release.

**Comment by auerswal** [comment]
The fping homepage still features an old man page version (still called `fping.1` instead of `fping.8`) with long fixed mistakes in it. I would have expected this issue to be easy to resolve, but perhaps you would rather close it as *won't fix*?

**Comment by schweikert** [comment]
I updated the documentation on the homepage. Sorry for the big delay (and thanks for the reporting the issue).
