### ISSUE TITLE
fping -Q does not output to standard output

### ISSUE THREAD

**Issue by ziqingkeshi** [schweikert/fping#262]
Hello,
Thank you very much for the program.
But I have encountered some problems with using fping,here is my system info:

**Linux version 3.10.0-1160.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Mon Oct 19 16:18:59 UTC 2020**

When I want to redirect the result of `fping -Q` command to a file, it didn't work, and output the result to the console,and there is no result in the file either.

![image](https://user-images.githubusercontent.com/41533033/185530509-b57a5d0a-e35b-404c-9477-05a49c9732fb.png)

I tried all kinds of methods, but they didn't work.Finally, I achieved by redirecting stderr:

![image](https://user-images.githubusercontent.com/41533033/185531957-c8d6e24f-fe46-44eb-8520-c5d1b74a62fc.png)

It looks like when "**-Q**" is used, the output results to standard error. This problem does not occur when the "**-Q**" parameter is not added, and the results can be obtained from standard output or redirected to a file normally.

I'm not sure if this is an issue and I've been able to achieve what I need, but I still want to figure out this phenomenon.

Looking forward to your reply.
Thank you very much！

**Comment by darless** [comment]
The `-Q` flag as you say uses stderr. This calls the `print_per_system_splits`. Using the `-N` flag uses `print_netdata`. With `-N` flag, stdout redirection works without having to redirect stderr. I do not know why it is important to use stderr with `print_per_system_splits`. I created a PR for this to change to stdout.

**Comment by schweikert** [comment]
While I agree that fping's use of stdout and stderr is not consistent and could be better, we can't change it now because it would break users calling fping programmatically (i.e. it changes its interface).
