### ISSUE TITLE
Cannot bind source address : cannot assign requested address

### ISSUE THREAD

**Issue by abhiverma866** [schweikert/fping#264]
I am trying to send ping messages to a host with source IP spoofed.
I am using : 
sudo fping -l eth0 --src 192.168.207.10 192.168.207.135

192.168.207.10  is spoofed IP (source)
192.168.207.135 is destination
 When I run the mentioned command linux return the following error:
Cannot bind source address : cannot assign requested address

**Comment by darless** [comment]
If you don't have the IP on the device you are running fping on, then that's the correct output. This is outside of fping, you'd see the same output if you try to use `ping -I <src> <dest>` if the <src> is not present to bind to.
