### ISSUE TITLE
-g option not working properly

### ISSUE THREAD

**Issue by robmori80** [schweikert/fping#278]
Tested version: fping: Version 5.1

Results:
┌──(kali㉿kali)-[~]
└─$ fping -a -g 37.59.174.224/28           
37.59.174.225
37.59.174.226
37.59.174.227
37.59.174.228
37.59.174.231
37.59.174.232
                                                                                                                                                            
┌──(kali㉿kali)-[~]
└─$ fping -a -g 37.59.174.224 37.59.174.239
37.59.174.225
37.59.174.226
37.59.174.227
37.59.174.228
37.59.174.231
37.59.174.232
37.59.174.239

The results should be the same; however, the last host does not appear in the first result.
Could this possibly be a bug in the tool?

**Comment by auerswal** [comment]
The IP 37.59.174.239 is the *broadcast* address of the given network 37.59.174.224/28 and thus excluded from the generated target hosts when using CIDR notation for `-g`.

**Comment by auerswal** [comment]
@robmori80: This does not seem to be an issue with fping. Can this issue be closed?

**Comment by robmori80** [comment]
Yes, of course. Tks
