### ISSUE TITLE
errors on fping version 5.1

### ISSUE THREAD

**Issue by punithadevi14** [schweikert/fping#309]
root@CHQS-vIHJAeHE53:~$ sudo fping google.com
setting SO_TIMESTAMPNS option: Protocol not available
setting SO_TIMESTAMPNS option (IPv6): Protocol not available
google.com is unreachable
root@CHQS-vIHJAeHE53:~$ fping --version
fping: Version 5.1

I am seeing this error when I am trying to ping the google.com. How can make the fping to work on my ubuntu

**Comment by gsnw** [comment]
Please check if `fping -4 google.com` works. I assume you do not have an IPv6 address on your system?
You can disable ipv6 over NetworkManager `/etc/NetworkManager/system-connections/` when you set `method=ignore` under `[ipv6]` category. This may help...

**Comment by punithadevi14** [comment]
root@CHQS-vIHJAeHE53:~$ fping -4 google.com
setting SO_TIMESTAMPNS option: Protocol not available
setting SO_TIMESTAMPNS option (IPv6): Protocol not available
google.com is unreachable

root@CHQS-vIHJAeHE53:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy


google is still unreachable

**Comment by gsnw** [comment]
Does a normal ping on google.com work?
`ping google.com`

I have check fping on my system Ubuntu 22.04.4 LTS and it works. Is your system a container or virtualmaschine?

**Comment by gsnw** [comment]
@schweikert Can be closed. Creator of the issue no longer responds.
