### ISSUE TITLE
Is it possible to provide official portable build ?

### ISSUE THREAD

**Issue by edwinjhlee** [schweikert/fping#322]
Hi, friends in fping community,

fping is awesome.
Is it possible to provide official portable build ?

We are developing [x-cmd](https://x-cmd.com), which provide portable tool for the users. x-cmd is implementing in posix shell/awk. 

Here is one example: 
https://www.x-cmd.com/pkg/nping

We can build fping according to the instructions provided in README. But adopting the official build binary can be more reliable in source; later positioning reported bugs by users will also be relatively easier.

Thank you.

**Comment by gsnw-sebast** [comment]
I had consulted with the project owner and it is planned to provide an official “portable version”.
This would have to be done by x-cmd or someone else.

**Comment by edwinjhlee** [comment]
> I had consulted with the project owner and it is planned to provide an official “portable version”. This would have to be done by x-cmd or someone else.

OK. Thank you for the feedback ~
