### ISSUE TITLE
Improve man page regarding differences for "default" and "none default" mode

### ISSUE THREAD

**Issue by zalexua** [schweikert/fping#33]
Call please somehow "none default" mode, for example as "batch" mode.
It will be easier to understand it and reference to it in description.

Start description of -B option as "Backoff factor. "+_current description_
Replace last sentence in description of -t option as: "Successive timeouts are multiplied by the backoff factor -B (only in default mode)"

Please describe _cleanly_ in man DESCRIPTION that there is two modes ("default" and "batch") with corresponding noticeable headers.
Mention please that they accept/ignore different options.
Add there some line breaks to better readability.

Clarify in description of every option which being accepted/ignored in "default" and "batch" modes.

For example -B option is ignored for "batch" mode, discussed here:
https://lists.oetiker.ch/pipermail/smokeping-users/2005-November/001723.html

Also, in any case details from another just created issue https://github.com/schweikert/fping/issues/32 have to be described in man page as well.

**Comment by zalexua** [comment]
Just a note:
One suggestion (3rd sentence) from current issue has been actually added in different commit - 
https://github.com/schweikert/fping/commit/c1fe95f7b768677ab971d3b8f0b4ec60d20690b6#diff-9e0aa608cc1becada2dee6fd8950ee85

Honestly, I don't consider this issue as fully considered and implemented.
Here is list of things were skipped:

> Call please somehow "none default" mode, for example as "batch" mode.
> It will be easier to understand it and reference to it in description.

> Please describe cleanly in man DESCRIPTION that there is two modes ("default" and "batch") with corresponding noticeable headers.
 > Mention please that they accept/ignore different options.
 > Add there some line breaks to better readability.

> Clarify in description of every option which being accepted/ignored in "default" and "batch" modes.

> For example -B option is ignored for "batch" mode, discussed here:
> https://lists.oetiker.ch/pipermail/smokeping-users/2005-November/001723.html

Currently (v3.10) man page use "looping or counting modes" phrase three times.
I think my suggestion about "batch mode" can be replaced by this already used phrase.
But everything quoted above - is still actual.

**Comment by zalexua** [comment]
What I found today - in the https://github.com/schweikert/fping/commit/609f4f17c4b896b86fe06bffc1d640b7d22e83c4 commit (when you closed this issue) you have added next to -t option:

> Note that this option has no effect looping or counting modes (-l, -c, or -C).

I originally requested to document this detail in different form (see description on top of page), and it would not provide so wrong sense !

But that's not true !
See:
```
# time fping -C3 -p1 -t300 yahoo.jp
yahoo.jp : [0], 84 bytes, 317 ms (317 avg, 66% loss)
yahoo.jp : [1], 84 bytes, 316 ms (317 avg, 33% loss)
yahoo.jp : [2], 84 bytes, 316 ms (316 avg, 0% loss)

yahoo.jp : 317.26 316.80 316.60

real    0m0.371s
user    0m0.000s
sys     0m0.000s

# time fping -C3 -p1 -t200 yahoo.jp

yahoo.jp : - - -

real    0m0.279s
user    0m0.000s
sys     0m0.000s
```
so -t option actually has effect when used with -c or -C options - but !!! only after last icmp request sent.
It's very connected with different issue https://github.com/schweikert/fping/issues/32

How to reopen current issue ?
Or should I open new one ?

**Comment by schweikert** [comment]
Issue #32 will be handled there. Please open a pull request for documentation improvement suggestions.
