### ISSUE TITLE
VSCode debugging does not work requires root rights

### ISSUE THREAD

**Issue by gsnw** [schweikert/fping#333]
Debugging in VSCode does not work because fping requires root rights.
Unfortunately, this was not taken into account during implementation.

Error message: `fping: can't create socket (must run as root?)`

**Comment by auerswal** [comment]
If `fping` requires root privileges (or the `NET_CAP_RAW` capability) should depend on the operating system and its configuration.

* On macOS, `fping` should not require root privileges.
* On systems with the kernel Linux, with a not too old kernel version, unprivileged operation also requires a suitable setting of the `net.ipv4.ping_group_range` kernel parameter. One of the group IDs of the `fping` process needs to be found inside the closed interval described by this parameter. Then `fping` should require neither root privileges nor `CAP_NET_RAW`.

**Comment by gsnw** [comment]
I had forgotten to check my sysctl.d files when reinstalling Linux.
The group ID has changed, so the net.ipv4.ping_group_range was no longer correct.

I didn't say anything, thanks
