### ISSUE TITLE
Test `ci/test-11-unpriv.pl` uses hard-coded copy destination and does not clean up afterwards

### ISSUE THREAD

**Issue by auerswal** [schweikert/fping#339]
The test `ci/test-11-unpriv.pl` uses a hard-coded destination of `/tmp/fping.copy` to create a binary with neither setuid bit nor capabilities. This copy is not removed, it remains after the tests have finished.

It would be preferable to use a randomized name, or to put the copy inside a temporary directory with a randomized name, using, e.g., mktemp(1) or equivalent Perl functionality. This file or directory should be deleted after testing to avoid accumulating more and more such copies.

**Comment by gsnw-sebast** [comment]
Maybe it is possible to identify in the Perl script whether the script is running under Github Action and then use `${{ runner.temp }}` as tmp dir?

$ENV{'TMP_DIR'} should be empty under Github Action

**Comment by auerswal** [comment]
Thanks for the idea! I'd prefer to have a solution that works the same on and off the GitHub-based CI, though.

Another idea could be to just use the `src/` directory where `fping` is built to create an unprivileged copy in, and remove it after the tests.

**Comment by gsnw-sebast** [comment]
The src/ directory is also possible, but would have to be taken into account when creating a release.
Which is done by deleting it after the successful test.
