### ISSUE TITLE
How do I build the HTML documentation?

### ISSUE THREAD

**Issue by marek22k** [schweikert/fping#349]
Hello,

I would like to build the HTML documentation as it can be found on https://fping.org/fping.8.html. How do I do that?

**Comment by gsnw-sebast** [comment]
You can convert manpage to html. For example with `man2html`

**Comment by marek22k** [comment]
I am new to the subject, how can this be done in concrete terms? I have only found a [.pod file](https://github.com/schweikert/fping/blob/develop/doc/fping.pod).

**Comment by gsnw-sebast** [comment]
Another way is for example use `pod2html` https://www.linux.org/docs/man1/pod2html.html

**Comment by marek22k** [comment]
Thank you, that worked. I have now used ``pod2html --noindex --infile=fping.pod --title="fping man-page"`` as the command to generate the HTML documentation (similar to the website).

**Comment by marek22k** [comment]
I was able to successfully build a Zeal/Dash compatible documentation for fping: https://mark22k.codeberg.page/zeal-docs/@fping/fping.xml
