### ISSUE TITLE
Build and test for Linux/ARM64

### ISSUE THREAD

**Issue by odidev** [schweikert/fping#358]
## Description  

For aarch64 platform, I have built "Fping" from source.  

## Steps   
Following "STEPS (https://github.com/schweikert/fping?tab=readme-ov-file#installation)" were used for building and installing Fping.  
```
wget https://github.com/schweikert/fping/archive/refs/tags/v4.0.tar.gz 
cd fping-4.0 
./autogen.sh 
./configure 
make 
make install 
```
## Outcome  

To validate that the build was successful we ran version check. The version info returned matched the expected value(s). 

`fping -v`
 
All this information was also added to Software Ecosystem Dashboard for Arm (https://www.arm.com/developer-hub/ecosystem-dashboard/).

**Comment by gsnw-sebast** [comment]
This is only an info message, so the comment will be closed.
