### ISSUE TITLE
--print-ttl --print-tos doesn't work with -l and -c options

### ISSUE THREAD

**Issue by O-ring** [schweikert/fping#367]
Hello everyone,

The --print-ttl --print-tos options do not work when the -c or -l parameters are used.

This is a working example:
fping   10.81.104.126 --print-ttl --print-tos  
10.81.104.126 is alive (TOS 72) (TTL 59)

This is a non-working example:
fping   10.81.104.126 --print-ttl --print-tos   -c 1
10.81.104.126 : [0], 64 bytes, 20.3 ms (20.3 avg, 0% loss)

Cheers,
Marco

**Comment by auerswal** [comment]
There is another output format that does not print TOS or TTL values: `-Q SECS, --squiet SECS`.

**Comment by auerswal** [comment]
> There is another output format that does not print TOS or TTL values: `-Q SECS, --squiet SECS`.

The output of `-c N`, `-C N`, and `-l` is per packet, and can show the packet's TOS and/or TTL, but the `-Q SECS` output is in general not per packet. Thus I'd say that `-Q SECS` should print neither TOS nor TTL.
