### ISSUE TITLE
AIX Support

### ISSUE THREAD

**Issue by blentzgh** [schweikert/fping#69]
We have a few glitches with building fping 3.10 on AIX; some existed back from the old source code (the problem with h_errno has existed forever!) and some are new problems introduced in the new 3.x chain (it looks like the getopt hooks are new).

I'm going to attach a quick diff I threw together to get fping 3.10 to build on my old AIX 5.3 system. 

Edit: Just realized the issue tracker doesn't support attachments; here's a GitHub Gist for you instead: https://gist.github.com/blentzgh/3aad6ab69069ccbff276

**Comment by schweikert** [comment]
Thanks for this (and sorry for being so late in integrating the patch)!
