### ISSUE TITLE
Typo in doc/fping.pod

### ISSUE THREAD

**Issue by evgkrsk** [schweikert/fping#75]
There is obvious typo in doc/fping.pod (and generated manpage as well):

```
Note that this option has no effect looping or counting modes (-l, -c, or -C).
```

**Comment by zalexua** [comment]
hmm, I cannot notice anything wrong.
What is the typo ?
Extra comma in "-c, or" ?

**Comment by evgkrsk** [comment]
Sorry, my bad. I mean that seems like word or two missed in between of "effect" and "looping". I cannot translate this sentence in my native language. What does this mean?

**Comment by zalexua** [comment]
The sentence has been added in https://github.com/schweikert/fping/commit/609f4f17c4b896b86fe06bffc1d640b7d22e83c4
Improvements requested by me in https://github.com/schweikert/fping/issues/33
But I'm not the author of the sentence.

Yes, I agree that would be better replace "effect looping" by "effect on looping".

**Comment by zalexua** [comment]
The new sentence appeared to be even absolutely wrong, as I described in last comment in the https://github.com/schweikert/fping/issues/33

**Comment by evgkrsk** [comment]
ping?

**Comment by schweikert** [comment]
This will be handled in #33
