### ISSUE TITLE
fping should support IPv6 transparently

### ISSUE THREAD

**Issue by cranderson** [schweikert/fping#80]
I'm not sure how I feel about this, but since Fedora is bugging me about it:

https://bugzilla.redhat.com/show_bug.cgi?id=1221496

Description of problem:

The current system of using different software (fping vs fping6) for different versions of the IP stack is broken.  As the IPv6 transition moves ahead its unreasonable to expect the user to do the IP address parsing and decide to use the appropriate tool for the address. 

fping should work like traceroute, ssh or all other applications supporting both protocol versions by default.

How reproducible:
Always

Steps to Reproduce:
1. fping 2a03:2880:20:4f06:face:b00c:0:1

Actual results:
2a03:2880:20:4f06:face:b00c:0:1 address not found

Expected results:
2a03:2880:20:4f06:face:b00c:0:1 is alive

**Comment by schweikert** [comment]
I agree... That's why I started a "unification" project a while ago:
https://github.com/schweikert/fping/issues/40
https://github.com/schweikert/fping/tree/feature/unify

Once the internal storage format is made the same, it should be easier to make fping support transparently both IPv4 and IPv6

**Comment by schweikert** [comment]
Implemented in develop branch and to be released with fping 3.16 (see also: fping-3.16-rc2)
