### ISSUE TITLE
Build from src

### ISSUE THREAD

**Issue by reinerotto** [schweikert/fping#87]
autoreconf -i
missing, when cloning from git, so no ./configure available.

**Comment by xtaran** [comment]
`autoreconf -i` is not missing. Have a look at [autogen.sh](https://github.com/schweikert/fping/blob/develop/autogen.sh).

`autogen.sh` is a common place to put commands necessary to generate the files necessary for building.

It's very common practice (and in general considered good practice) to not include any generated file in a git repository, only in the released tar balls.

I'd be happy if fping's git repository would stay as clean as it is with regards to generated files.

**Comment by reinerotto** [comment]
It is old practice, to either to supply correct docs, or none. Docs, which assume the reader to know already part of the proedure, are not very helpful.
I refere to
"If you want to install fping from source, proceed as follows:
    Run ./configure with the correct arguments (see: ./configure --help)
    Run make; make install"

Which should better read

"If you want to install fping from source, proceed as follows:
autoreconf -i
Run ./configure with the correct arguments (see: ./configure --help)
...."
