### ISSUE TITLE
Exit status is no longer set to 2 when host name cannot be resolved to an IP

### ISSUE THREAD

**Issue by NetworkEng** [schweikert/fping#92]
The man page indicates, fping should "Exit status ... 2 if any IP addresses were not found...".  Starting in version 3.10, the exit status is no longer set to 2 when the host name to IP resolution fails.  I've tested this on both RHEL and Mac OS X.

E.g.:
**v3.9 (working as expected)**

```
rhel6.2$ fping -v
fping: Version 3.9
fping: comments to david@schweikert.ch
rhel6.2$ fping cannotresolve
cannotresolve address not found
rhel6.2$ echo $?
2
rhel6.2$
```

**v3.10**

```
rhel6.2$ fping -v
fping: Version 3.10
fping: comments to david@schweikert.ch
rhel6.2$ fping cannotresolve
cannotresolve address not found
rhel6.2$ echo $?
1
rhel6.2$
```

It appears that this commit (line 797 of fping.c) on April 14, 2014 is the culprit:
[https://github.com/schweikert/fping/commit/3cf9a8a3cd29c1110070fd90fe293f2705e14b62](url)

```
796    if( !num_hosts )
797        exit(1);
```

If I edit fping.c of the version 3.10 source, and revert it to exit(2), it then reverts to the expected behavior.

```
rhel6.2$ fping -v
fping: Version 3.10
fping: comments to david@schweikert.ch
rhel6.2$ fping cannotresolve
cannotresolve address not found
rhel6.2$ echo $?
2
rhel6.2$
```

Could someone please investigate exit status codes and fix and/or enhance them and any required documentation?

Thanks for the great work are doing, and thanks in advance for your help in getting this resolved.
-Matt

**Comment by schweikert** [comment]
Fixed in develop branch
