### ISSUE TITLE
show last reacheable hop when destination is unreachable

### ISSUE THREAD

**Issue by thc2cat** [schweikert/fping#93]
i'd don't know if it's very difficult to do, but maybe it's possible to print last icmp hop when a host is unreachable.

fping XX.XX.XX.XX
XX.XX.XX.XX  is unreachable (lost after YYY.YYY.YYY.YYY )

**Comment by schweikert** [comment]
This would require doing traceroutes instead of pings. I don't see it as feasible (but see also: #71)
