### ISSUE TITLE
Some fping result sent to file using -L option dont have linefeeds

### ISSUE THREAD

**Issue by dshoski** [schweikert/fping#94]
Hi, 
When I output to a file most of the time it inserts a linefeed between pings but in some cases I see:
"sendto() - A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.2016/03/23 10:50:37.109 : Reply[23] from 192.168.63.19: bytes=1200 time=337.5 ms TTL=60 hops=4"
Note that in this case the next ping reply is on the same line as the socket error message. I have also see the case where I get multiple socket errors before a good ping and they all have no linefeed.
Note that for a timeout error I do see a linefeed, so this linefeed issue is specific to this type of socket error.
Can you reply if this is indeed an FPing problem?
Thanks! Dean

**Comment by schweikert** [comment]
What platform are you running fping on?
